config/routes.rb
Rails.application.routes.draw do
  # get ':controller(/:action(/:id))'
  root to: "items#index"
  resources :items

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  validates :user,    presence: true
  validates :user_id, uniqueness: true

  has_many :positions
  has_many :items, through: :positions

  has_and_belongs_to_many :items

  def add_item(i)
    if items.include?(i)
      positions.where(item_id: i.id).first.increment!(:quantity)
    else
      positions.create(item: i, quantity: 1)
    end
  end

  def remove_position(position_to_remove_id)
    positions.where(item_id: position_to_remove_id).first.try(:destroy)
  end

  def remove_item(i)
    if items.include?(i)
      positions.where(item_id: i.id).first.decrement!(:quantity)
    else
      positions.delete(item: i, quantity: 1)
    end
  end
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :price, :weight, numericality: { greater_than: 0 }, presence: true
  
  has_many :positions
  has_many :carts, through: :positions
  has_many :images, as: :imageable

  has_and_belongs_to_many :carts
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :item
  belongs_to :cart
end

app/models/user.rb
class User < ApplicationRecord
  has_one  :cart
  has_many :orders, dependent: :destroy
  has_many :images, as: :imageable
end

app/models/virtual_item.rb
class VirtualItem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def hello
    @variable = "#{params[:first_name]}"

    @items_count = Item.count
    render html: "ItemsController #{params[:first_name]} #{params[:family_name]} ! #{@variable } #{@items_count} #{params}"
  end

  def index
    @items = Item

    # Only active
    @items = @items.where(active: true)
    
    # Set order
    order = params[:order] == "asc" ? "asc" : "desc"
    @items = @items.order("created_at #{order}")

    @items = Item.paginate(per_page: 5, page: params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.create(item_params)
    if @item.errors.empty?
      redirect_to @item
    else
      render "new"
    end
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update_attributes(item_params)
    if @item.errors.empty?
      redirect_to @item
    else
      render "edit"
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  private

  def item_params
    allow = [:name, :description, :price, :weight]
    params.require(:item).permit(allow)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/1hello.html.erb
<%# "This is ItemsController speaking, hello!" %>



<%= params[:first_name] %>
<%= params[:family_name] %>

<h1>This is ItemsController speaking</h1>

<%= @variable %>

<p>
Hello, <%= params[:first_name] %>
<%# <%= params[:first_name] %>

<%# <%= params[:family_name] %>
</p>

<p>We have <%= @items_count %> items in our store!</p>

app/views/items/_form.html.erb
  Name:  <br>
  <%= f.text_field :name %>  <br><br>
  Description:  <br>
  <%= f.text_field :description %>  <br><br>
  Price:  <br>
  <%= f.text_field :price %>  <br><br>  
  Weight:  <br>
  <%= f.text_field :weight %>  <br><br>

app/views/items/edit.html.erb
<h1>Редактирование товара</h1>
<%= form_for @item do |f| %>
  <%= render partial: "form", locals: { f: f } %>
  <%= f.submit "Сохранить товар" %>
<% end %>

app/views/items/hello.html.erb
<%# "This is ItemsController speaking, hello!" %>


<%= params %>
<br>
<br>


<h1>This is ItemsController speaking</h1>

<%= @variable %>

<p>
Hello, <%= params[:first_name] params[:family_name] %>

</p>

<p>We have <%= @items_count %> items in our store!</p>

app/views/items/index.html.erb
<h1>Все товары</h1>
<%= link_to 'Создать новый товар', new_item_path %>
<p>
  Сортировка:
  <%= link_to "Новые сверху", items_path(order: "desc") %> |
  <%= link_to "Старые сверху", items_path(order: "asc") %>
</p>
<ul>
  <% @items.each do |i| %>
    <li><%= link_to i.name, i %></li>
  <% end %>
</ul>
<%= will_paginate @items %>

app/views/items/new.html.erb
<h1>Создание нового товара</h1>
<%= form_for @item do |f| %>
  <%= render partial: "form", locals: { f: f } %>
  <%= f.submit "Создать товар" %>
<% end %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<p>Описание: <%= @item.description %></p>
<p>Цена: <b><%= @item.price %></b></p>
<p>Вес: <b><%= @item.weight %></b></p>


<%= link_to "Редактировать товар", edit_item_path(@item) %>
<br>
<%= link_to "Удалить товар", item_path(@item),
method: :delete, data: { confirm: "Уверены?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<%= link_to "главная", root_path %>

  <body>
    <%= yield %>
  </body>
</html>